
name: Build-Artifacts

on: 
  workflow_dispatch:
    inputs:
      version: 
        type: string

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Release
      uses: softprops/action-gh-release@v1
      with: 
        name: ${{ github.event.inputs.version }}-${{matrix.os}}
        tag_name: ${{ github.event.inputs.version }}-${{matrix.os}}
        files: |
          ./artifacts/drivelist.zip
          ./artifacts/cpu-features.zip
          ./artifacts/find-git-repositories.zip
          ./artifacts/keytar.zip
          ./artifacts/node-pty.zip
          ./artifacts/nsfw.zip
          